# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template enums.py.jinja --
from ._compat import StrEnum


class ApplicationStatus(StrEnum):
    APPLIED = 'APPLIED'
    MATCHED = 'MATCHED'
    REJECTED = 'REJECTED'
    OFFERED = 'OFFERED'
    ACCEPTED = 'ACCEPTED'

class Currency(StrEnum):
    USD = 'USD'
    EUR = 'EUR'
    GBP = 'GBP'
    INR = 'INR'

class JobStatus(StrEnum):
    ACTIVE = 'ACTIVE'
    INACTIVE = 'INACTIVE'
    IN_REVIEW = 'IN_REVIEW'

class JobType(StrEnum):
    FULL_TIME = 'FULL_TIME'
    PART_TIME = 'PART_TIME'
    CONTRACT = 'CONTRACT'
    INTERNSHIP = 'INTERNSHIP'

class WorkMode(StrEnum):
    REMOTE = 'REMOTE'
    ONSITE = 'ONSITE'
    HYBRID = 'HYBRID'

class EmployeeCount(StrEnum):
    ONE_TO_TEN = 'ONE_TO_TEN'
    ELEVEN_TO_FIFTY = 'ELEVEN_TO_FIFTY'
    FIFTY_ONE_TO_TWO_HUNDRED = 'FIFTY_ONE_TO_TWO_HUNDRED'
    TWO_HUNDRED_AND_ONE_TO_FIVE_HUNDRED = 'TWO_HUNDRED_AND_ONE_TO_FIVE_HUNDRED'
    FIVE_HUNDRED_AND_ONE_TO_ONE_THOUSAND = 'FIVE_HUNDRED_AND_ONE_TO_ONE_THOUSAND'
    ONE_THOUSAND_AND_ONE_TO_FIVE_THOUSAND = 'ONE_THOUSAND_AND_ONE_TO_FIVE_THOUSAND'
    FIVE_THOUSAND_AND_ONE_TO_TEN_THOUSAND = 'FIVE_THOUSAND_AND_ONE_TO_TEN_THOUSAND'
    TEN_THOUSAND_AND_ONE_PLUS = 'TEN_THOUSAND_AND_ONE_PLUS'

class PayInterval(StrEnum):
    HOURLY = 'HOURLY'
    DAILY = 'DAILY'
    WEEKLY = 'WEEKLY'
    MONTHLY = 'MONTHLY'
    YEARLY = 'YEARLY'

