from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'Company',
    'JobApplication',
    'JobPost',
    'JobTracker',
    'Tag',
    'UploadedCv',
    'User',
    'WorkExperience',
    'Account',
    'Session',
    'VerificationToken',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'Company': {
        'User': 'User',
        'JobPost': 'JobPost',
    },
    'JobApplication': {
        'JobPost': 'JobPost',
        'User': 'User',
    },
    'JobPost': {
        'JobApplication': 'JobApplication',
        'Company': 'Company',
        'JobTracker': 'JobTracker',
        'Tag': 'Tag',
    },
    'JobTracker': {
        'JobPost': 'JobPost',
        'User': 'User',
    },
    'Tag': {
        'JobPost': 'JobPost',
    },
    'UploadedCv': {
        'User': 'User',
    },
    'User': {
        'Account': 'Account',
        'Company': 'Company',
        'JobApplication': 'JobApplication',
        'JobTracker': 'JobTracker',
        'Session': 'Session',
        'UploadedCv': 'UploadedCv',
        'WorkExperience': 'WorkExperience',
    },
    'WorkExperience': {
        'User': 'User',
    },
    'Account': {
        'User': 'User',
    },
    'Session': {
        'User': 'User',
    },
    'VerificationToken': {
    },
}

# fmt: on